### ISSUE TITLE
Add UnitTests for TypeExtractors of new Java API

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#579]
The generation of serializers and comparators for the new Java API depends a lot on automatic type extraction.
The type extraction needs thorough testing to avoid hard to debug serialization problems.

**Comment by twalthr** [comment]
At the moment I tested the following types, some types are not handled correctly (no exception is thrown):

Supported types:
- basic types (String, Boolean, Integer etc.)
- tuple with basic types
- tuple with tuples
- subclass of tuple
- custom type
- value type
- tuple of values

Types not implemented (yet):
- array
- tuples with arrays
- custom types with generics
- usage of functions like `class MapFunctionImpl<X, T> extends MapFunction<X, T>` and
      `MapFunction<?, ?> function = new MapFunctionImpl<String, String>();` -> TypeExtractor, returns null

Unintended usage of API:
- missing generics in operator function -> "Generic function base class must be immediate super class." Error message should be improved. Not user-friendly.
- missing generics in tuple -> No exception, but TypeExtractor returns null
- usage of Tuple in generics (`MapFunction<X, Tuple>`) -> No exception, but TypeExtractor returns null
- usage of Value in generics (`MapFunction<X, Value>`) -> TypeExtractor returns `ValueType<eu.stratosphere.types.Value>`

Do you have other cases I could test?

**Comment by StephanEwen** [comment]
Please add also Types that implement Hadoop's `Writable` interface. They should have a special serializer that calls the `write()` and `readFields()` method.

**Comment by StephanEwen** [comment]
How about the following cases (I tried to prioritize them)
- Tuples of custom types, such as `Tuple2<Long, MyJavaClass>`
- Cases where the generic parameters are not in the immediate superclasse:

```
public class LongKeyValue<V> extends Tuple2<Long, V> {
...
}

public class MyPair extends LonkKeyValue<String> {
...
}
```
- Functions where the return type is dependent on the input type. The type extractor interface needs to be extended to take the input type in order to produce the return type:

```
public class IdentityMapper<T> extends MapFunction<T, T> {
...
}
```
- Cases where parts of the return type depend on the input type:

```
public class OneAppender<T> extends MapFunction<T, Tuple2<T, Integer>> {
    public Tuple2<T, Integer> map(T value) {
        return new Tuple2<T, Integer>(value, 1);
    }
}
```

**Comment by StephanEwen** [comment]
- Input type may be in the output type multiple times

```
public class FieldDuplicator<T> extends Mapper<T, Tuple2<T, T>> {
    public Tuple2<T, T> map(T value) {
        return new Tuple2<T, T>(value, value);
    }
}
```

**Comment by StephanEwen** [comment]
### For the cases that we do not support, please give specific error messages for the following cases:
- If someone uses `Tuple`, rather than a specific type of tuple.
- If the type is abstract or an interface
- If the type cannot be found out and does not depend on the input type: `public class MyMapper<E> extends MapFunction<String, E> {}`

**Comment by twalthr** [comment]
I have rewritten most of the TypeExtractor, but now I'm facing a problem. The TypeExtractor is now able to realize TypeVariables and can e.g. extract the return type of a IdentityMapper mentioned above.

This does work correctly:

``` java
IdentityMapper<Boolean> function = new IdentityMapper<Boolean>(){ /* nothing in here */ };
TypeInformation<?> ti = TypeExtractor.getMapReturnTypes(function);
```

This doesn't work:

``` java
IdentityMapper<Boolean> function = new IdentityMapper<Boolean>();
TypeInformation<?> ti = TypeExtractor.getMapReturnTypes(function);
```

I think this is due to type erasure, right? How should I handle this case exactly?

**Comment by twalthr** [comment]
I implemented it the following way, I hope this is ok?

``` java
IdentityMapper<String> function = new IdentityMapper<String>();

TypeInformation<?> ti = TypeExtractor.getMapReturnTypes(function, BasicTypeInfo.STRING_TYPE_INFO);

```

**Comment by twalthr** [comment]
@StephanEwen In which package should I put a Writable Type? If it should be in the same package than the other types, I need to add a 'hadoop-common' dependency to the Java API...is this intended? If yes, which version?

**Comment by twalthr** [comment]
Should `GenericArrayType`s be supported? Theoretically it is possible to extract the TypeInformation from:

``` java
MapFunction<?, ?> function = new MapFunction<String, Tuple2<String, String>[]>() {
    private static final long serialVersionUID = 1L;

    @Override
    public Tuple2<String, String>[] map(String value) throws Exception {
        return null;
    }               
};

TypeInformation<?> ti = TypeExtractor.getMapReturnTypes(function, null);
```

But the `ArrayTypeInfo` currently does not provide the API for that.

**Comment by twalthr** [comment]
How should I treat custom objects with generics?

``` java
public class MyObject<T> {
    public T myField;
}

@Test
public void testParamertizedCustomObject() {
    MapFunction<?, ?> function = new MapFunction<Boolean, MyObject<String>>() {
        private static final long serialVersionUID = 1L;

        @Override
        public MyObject<String> map(Boolean value) throws Exception {
            return null;
        }
    };

    TypeInformation<?> ti = TypeExtractor.getMapReturnTypes(function, null);
    System.out.println(ti);
}
```

At the moment I create a GenericTypeInfo with the raw object (without generics). Is this ok? Or should I throw an Exception that this is not suported?

**Comment by StephanEwen** [comment]
I think that is fine from our side. The generic types go right now to Avro.
Can you check if Avro can handle them? If yes, we are good...

**Comment by StephanEwen** [comment]
Done in b3e405f22cd0101e111c8ede8d04621d8ada33d3

**Comment by twalthr** [comment]
Actually this issue is not done completely as 

"Please add also Types that implement Hadoop's Writable interface. They should have a special serializer that calls the write() and readFields() method."

is still missing. I will open a separate issue for this.
